
export const pokemonDecksMock = [
  { name: "Pikarom", description: "Pikachu & Zekrom-GX deck focused on fast energy acceleration." },
  { name: "Eternatus VMAX", description: "Dark-type deck utilizing Eternatus VMAX for high damage output." },
  { name: "Shadow Rider Calyrex", description: "Psychic deck with energy acceleration and draw power." },
  { name: "Arceus Duraludon", description: "Tanky deck with Arceus VSTAR and Duraludon VMAX." },
  { name: "Lugia VSTAR", description: "Strong energy acceleration deck using Archeops." },
  { name: "Mew VMAX", description: "Fusion Strike deck with Genesect V for insane draw power." },
  { name: "Lost Zone Box", description: "A versatile deck utilizing Comfey and Sableye." },
  { name: "Regigigas", description: "A deck focusing on Regigigas and the Regis for massive power plays." },
  { name: "Blissey Miltank", description: "A tanky deck with high HP Pokémon and healing strategies." },
  { name: "Charizard ex", description: "Fire-type deck built around Charizard ex." },
  { name: "Gardevoir ex", description: "Psychic deck utilizing Gardevoir ex for energy acceleration." },
  { name: "Miraidon ex", description: "Electric deck with Miraidon ex for fast setup." },
  { name: "Chien-Pao ex", description: "Water deck focusing on energy acceleration and high damage." },
  { name: "Giratina VSTAR", description: "Lost Zone deck featuring Giratina’s strong attacks." },
  { name: "Palkia VSTAR", description: "Water deck with powerful bench damage." },
  { name: "Dialga VSTAR", description: "Metal deck with a strong extra-turn ability." },
  { name: "Zacian VSTAR", description: "Metal deck with Zacian's powerful attacks." },
  { name: "Urshifu VMAX", description: "Rapid Strike deck utilizing Urshifu’s spread damage." },
  { name: "Sylveon VMAX", description: "Colorful deck using Rapid Strike synergy." },
  { name: "Hisuian Zoroark VSTAR", description: "A deck that takes advantage of damage counters." },
  { name: "Rayquaza VMAX", description: "Dragon-type deck with high damage potential." },
  { name: "Kyogre Lost Zone", description: "A powerful late-game finisher deck using Lost Zone mechanics." },
  { name: "Zoroark Toolbox", description: "A flexible deck using Zoroark’s evolution abilities." },
  { name: "Goodra VSTAR", description: "A tanky deck with strong defensive plays." },
  { name: "Darkrai VSTAR", description: "Dark-type deck focusing on energy acceleration." },
  { name: "Regidrago VSTAR", description: "Dragon deck utilizing attacks from the discard pile." },
  { name: "Gengar VMAX", description: "Dark deck that leverages Gengar’s high damage." },
  { name: "Rillaboom VMAX", description: "Grass deck with energy acceleration." },
  { name: "Venusaur VMAX", description: "A Grass deck built around status effects." },
  { name: "Inteleon VMAX", description: "A Water deck using sniping abilities." },
  { name: "Alcremie VMAX", description: "Fairy deck with high-energy requirements but strong potential." },
  { name: "Togekiss VMAX", description: "A control deck focused on consistency." },
  { name: "Duraludon VMAX", description: "A Metal deck with an anti-special energy mechanic." },
  { name: "Flying Pikachu VMAX", description: "An anti-meta deck with Flying Pikachu’s immunity." },
  { name: "Single Strike Urshifu", description: "A heavy-hitting deck with high damage potential." },
  { name: "Boltund VMAX", description: "Lightning deck focusing on energy acceleration." },
  { name: "Zarude V", description: "Grass deck built around healing strategies." },
  { name: "Snorlax Control", description: "A deck designed to stall and disrupt opponents." },
  { name: "Dragapult VMAX", description: "A Psychic deck with spreading damage strategy." },
  { name: "Greninja V-Union", description: "A Water deck utilizing Greninja’s multiple attacks." },
  { name: "Mewtwo V-Union", description: "A Psychic deck with a tanky Mewtwo setup." },
  { name: "Lunatone & Solrock", description: "A budget-friendly deck using Sun Energy for acceleration." },
  { name: "Rotom VSTAR", description: "Electric deck using discarded tools for damage." },
  { name: "Beedrill Single Strike", description: "A deck focusing on Beedrill’s OHKO potential." },
  { name: "Aerodactyl VSTAR", description: "A disruptive deck with a strong ability." },
  { name: "Trevenant VMAX", description: "A control deck built around energy denial." },
  { name: "Whimsicott VSTAR", description: "A deck designed to lock down opponents’ energy plays." },
  { name: "Kingdra Spread", description: "A Water deck utilizing Kingdra’s spread damage." },
  { name: "Houndoom Single Strike", description: "A strong dark deck with Single Strike support." },
  { name: "Malamar Rapid Strike", description: "A deck focusing on attacking with Rapid Strike cards." },
  { name: "Shiftry Mill", description: "A deck focused on milling the opponent’s deck." },
  { name: "Ditto Toolbox", description: "A flexible deck using Ditto’s transformation ability." },
  { name: "Copperajah VMAX", description: "A tanky Metal deck with high damage output." },
  { name: "Delphox V", description: "A deck using Lost Zone mechanics with fire spread damage." },
  { name: "Dracozolt VMAX", description: "A Lightning deck focused on punishing opponents." },
  { name: "Falinks Rapid Strike", description: "A swarming deck using Falinks' synergy." },
  { name: "Crobat VMAX", description: "A dark deck utilizing Crobat’s draw power." },
  { name: "Slowking VMAX", description: "A Poison-based deck that deals chip damage over time." },
  { name: "Butterfree VMAX", description: "A status effect deck utilizing poison and burn." },
  { name: "Wailord V", description: "A Water deck featuring high HP Pokémon." },
  { name: "Persian Control", description: "A deck designed to manipulate opponent resources." },
  { name: "Kecleon Toolbox", description: "A fun deck using Kecleon’s type-changing ability." },
  { name: "Aegislash VMAX", description: "A deck focused on multiple attack modes." },
  { name: "Flapple VMAX", description: "A Grass deck utilizing Apple Drop abilities." },
  { name: "Cinderace VMAX", description: "A Fire deck with a strong counterattack ability." },
  { name: "Jolteon VMAX", description: "An Electric deck with bench sniping power." },
  { name: "Coalossal VMAX", description: "A tanky deck using Coalossal’s high HP." },
  { name: "Morpeko Control", description: "A disruptive deck that focuses on energy denial." },
  { name: "Obstagoon Lock", description: "A deck using Obstagoon to block opponent attacks." },
  { name: "Alolan Exeggutor", description: "A fun Grass deck focusing on disruption." },
  { name: "Rapidash V", description: "A Fire deck built around status effects." },
  { name: "Xerneas Fairy Box", description: "A deck using multiple Fairy attackers." },
  { name: "Decidueye VSTAR", description: "A Grass deck with a powerful snipe attack." }
];
